[build]
  command = "cp -R public static/"
  publish = "static"
  functions = "netlify/functions"

[functions]
  python_version = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
